<h3>Numpy</h3>

TODO: Small numpy intro
Numpy is the standard language for  in python. 
Most of python's libraries for data science are built on top of numpy

In [89]:
import numpy as np

<h4> Data types </h4>

TODO: a small intro on data types

Similarly to a list, an array is a sequence of elements. All elements in a numpy array are of the same data type. We can define the precision in bytes of a the elements 

In [102]:
int_array_1 = np.array([3,4,5,6,7], np.int16)
print(int_array_1.dtype)

In [ ]:
int_array_3 = np.array([11,13,2,1], np.int16)
print(int_array_3.dtype)

In [ ]:
int_array_4 = np.array([11,13,2,1], np.int16)
print(int_array_4.dtype)

In [40]:
my_int_array = np.array([3,4,5,6,7,8,9])
print(my_int_array.dtype)

int64


In [41]:
float_array_1 = np.array([2.3, 4.3, 1.3], dtype=np.float16)
print(float_array_1.dtype)

float16


In [42]:
float_array_2 = np.array([2.3, 4.3, 1.3], dtype=np.float32)
print(float_array_2.dtype)

float32


In [43]:
my_float_array = np.array([32.3,43.1,9])
print(my_float_array.dtype)

float64


<h4> Indexing and slicing </h4>
To access elements inside a numpy array we use indexing:

In [44]:
print(my_int_array)
print(my_int_array[0])
print(my_int_array[2])
print(my_int_array[-1])
print(my_int_array[-3])

[3 4 5 6 7 8 9]
3
5
9
7


We can redefine an element in an array by selecting its index and assigning it to a new value:

In [46]:
print(my_int_array)


[3 4 5 6 7 8 9]


To access multiple elements at a time we use slicing:

In [118]:
print(my_int_array)
print(my_int_array[2:4])
print(my_int_array[1:5])
print(my_int_array[:4])
print(my_int_array[2:])
print(my_int_array[-3:])

[3 4 5 6 7 8 9]
[5 6]
[4 5 6 7]
[3 4 5 6]
[5 6 7 8 9]
[7 8 9]


Similarly, 

<h4>Multi-dimensional arrays</h4>

In [26]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(my_matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


We use multiple indices to access elements of multidimensional arrays. In the case of a 2D matrix, the first index refers to the row index, while the second one is for the columns:

In [27]:
print(my_matrix[1,2])
print(my_matrix[-1,-1])

6
12


If we use only one index we can select entire rows:

In [28]:
print(my_matrix[0])
print(my_matrix[1:3])

[1 2 3]
[[4 5 6]
 [7 8 9]]


If we want to select an entire column:

In [29]:
print(my_matrix[:,0])

[ 1  4  7 10]


Similarly, for 3 dimensional arrays:

In [47]:
multidim_array = np.array([
    [[3,4,2],[5,4,4]],
    [[7,8,7],[6,6,6]]
])

Now our array consists of 2 2x3 matrices. This means that element at index 0 is the first 2x3 matrix, and element at index 1 is the second 2x3 matrix. We can then access the elements of the matrix as before:

In [79]:
print(multidim_array)
print('')
print(multidim_array[0])
print(multidim_array[0,:,1])
print(multidim_array[1,-1,:])

[[[3 4 2]
  [5 4 4]]

 [[7 8 7]
  [6 6 6]]]

[[3 4 2]
 [5 4 4]]
[4 4]
[6 6 6]


<h4>Dimensions</h4>

A convenient way to keep track of the operations that we perform is to check the dimension of input, intermediate or output arrays. Numpy provides an easy way to see the shape of an array:

In [31]:
my_matrix.shape

(4, 3)

In [49]:
multidim_array.shape

(2, 2, 3)

To look at the number of dimensions:

In [33]:
my_matrix.ndim

2

In [52]:
multidim_array.ndim

3

In [80]:
my_int_array.ndim

1

<h4>Zeros, ones, arange</h4>

With numpy we can easily create arrays of zeros, ones and evenly spaced values:

In [67]:
array_zeros = np.zeros(10)
print(array_zeros)
matrix_zeros = np.zeros((5,5))
matrix_zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [68]:
array_ones = np.ones(10)
print(array_ones)
matrix_ones = np.ones((5,5))
matrix_ones

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [72]:
np.arange(4,10,2)

array([4, 6, 8])

The third argument in `np.arange` is the step size.

TODO:

<h4> Reshape </h4>

<h4>Boolean arrays</h4>

Numpy arrays can also be booleans. We can use arrays as indices

<h4>Operations</h4>

TODO: add/subtract/multiply/divide by number, multiply two arrays elementwise

<h4> Broadcasting </h4>

<h4>Basic numpy functions</h4>
min, max, mean, std, var. Mention axis

<h4> Practice numpy </h4>

TODO: add exercises

<h4>Univariate linear regression</h4>

We want to use a linear model to estimate the price of a house given its surface in square meters. We are given the following data:

In [57]:
square_meters = np.array([50, 51, 62, 78, 81, 85, 101, 102, 120, 135, 141, 170])
price = np.array([
    180000,
    172000,
    240000,
    340000,
    315000,
    320000,
    400000,
    410000,
    410000,
    535000,
    560000,
    700000,
])

**1 - Do a scatter plot with your data showing the price of each house**

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html

In [56]:
import matplotlib.pyplot as plt
# your code goes here
# for subscript 2 use \u00b2

In our linear regression model:

\begin{equation}
\bar{y} = ax + b
\end{equation}

we can compute the coefficients $a$ and $b$ following the ordinary least squares method using the following expressions:
\begin{equation}
a = \frac{\sum_{i=0}^n(x_i+\bar{x})(y_i-\bar{y})}{\sum_{i=0}^n(x_i-\bar{x})^2}
\end{equation}

\begin{equation}
b = \bar{y} - a\bar{x}
\end{equation}

$\bar{x} = mean(x)$, $\bar{y} = mean(y)$

**2 - Compute the coefficients $a$ and $b$ and plot the estimation of the house prices on top of the scatter plot**

<h4>Sklearn linear regression</h4>

We will now use the build-in linear regression model from Sklearn. Taken from the documentation page https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html:

"Ordinary least squares Linear Regression.

LinearRegression fits a linear model with coefficients w = (w1, …, wp) to minimize the residual sum of squares between the observed targets in the dataset, and the targets predicted by the linear approximation."

In [58]:
from sklearn.linear_model import LinearRegression

linear_regression = LinearRegression()
X = square_meters.reshape(-1,1)
y = price.reshape(-1,1)
linear_regression.fit(X, y)
y_pred = linear_regression.predict(X)

In [60]:
linear_regression.coef_

array([[4137.62999101]])

In [59]:
linear_regression.intercept_

array([-23654.40578594])

<h5>Extra exercise</h5>

Write your own univariate linear model class. It should have two methods: a `fit` method that allows you to fit your model given some X and y (it should update the attributes `a` and `b`) and a predict method in which you can use the trained model to predict new y given X. Create an instance of the class, fit it with `square_meters`, `price` data and predict the  price for the following houses:

In [53]:
new_houses = np.array([66, 72, 128, 425])

Do you get the same coefficients as before?

In [54]:
class LinearModel:
    def __init__(self):
        self.a = 0
        self.b = 0
    
    def fit(self, X, y):
        # write your code here
        pass
    
    def predict(self, X):
        # write your code here
        pass

<h4>Mean squared error</h4>

The mean squared error is defined as follows:

\begin{equation}
\frac{1}{n}\sum_{i=0}^{n}(Y_i - \hat{Y}_i)^2
\end{equation}

**1 - Compute the mean squared error of the linear regression model that we just fitted**

**2 - Use sklearn's mean squared error function and compare the results with the previous one**

<h4> Pandas </h4>

The two primary data structures in pandas as Series and Dataframes, which allow for efficient handling and manipulation of tabular data. Let's see how we can use pandas to load and treat data from a dataset of breast tumor cells.

In [85]:
import pandas as pd

breast_cancer = pd.read_csv('breast_cancer.csv')

In [86]:
breast_cancer

x.radius_mean  x.texture_mean  x.perimeter_mean  x.area_mean  \
0           13.540           14.36             87.46        566.3   
1           13.080           15.71             85.63        520.0   
2            9.504           12.44             60.34        273.9   
3           13.030           18.42             82.61        523.8   
4            8.196           16.84             51.71        201.9   
..             ...             ...               ...          ...   
564         20.920           25.09            143.00       1347.0   
565         21.560           22.39            142.00       1479.0   
566         20.130           28.25            131.20       1261.0   
567         16.600           28.08            108.30        858.1   
568         20.600           29.33            140.10       1265.0   

     x.smoothness_mean  x.compactness_mean  x.concavity_mean  \
0              0.09779             0.08129           0.06664   
1              0.10750             0.12700           0.04568   
2              0.10240             0.06492           0.02956   
3              0.08983             0.03766           0.02562   
4              0.08600             0.05943           0.01588   
..                 ...                 ...               ...   
564            0.10990             0.22360           0.31740   
565            0.11100             0.11590           0.24390   
566            0.09780             0.10340           0.14400   
567            0.08455             0.10230           0.09251   
568            0.11780             0.27700           0.35140   

     x.concave_pts_mean  x.symmetry_mean  x.fractal_dim_mean  ...  \
0              0.047810           0.1885             0.05766  ...   
1              0.031100           0.1967             0.06811  ...   
2              0.020760           0.1815             0.06905  ...   
3              0.029230           0.1467             0.05863  ...   
4              0.005917           0.1769             0.06503  ...   
..                  ...              ...                 ...  ...   
564            0.147400           0.2149             0.06879  ...   
565            0.138900           0.1726             0.05623  ...   
566            0.097910           0.1752             0.05533  ...   
567            0.053020           0.1590             0.05648  ...   
568            0.152000           0.2397             0.07016  ...   

     x.texture_worst  x.perimeter_worst  x.area_worst  x.smoothness_worst  \
0              19.26              99.70         711.2             0.14400   
1              20.49              96.09         630.5             0.13120   
2              15.66              65.13         314.9             0.13240   
3              22.81              84.46         545.9             0.09701   
4              21.96              57.26         242.2             0.12970   
..               ...                ...           ...                 ...   
564            29.41             179.10        1819.0             0.14070   
565            26.40             166.10        2027.0             0.14100   
566            38.25             155.00        1731.0             0.11660   
567            34.12             126.70        1124.0             0.11390   
568            39.42             184.60        1821.0             0.16500   

     x.compactness_worst  x.concavity_worst  x.concave_pts_worst  \
0                0.17730            0.23900              0.12880   
1                0.27760            0.18900              0.07283   
2                0.11480            0.08867              0.06227   
3                0.04619            0.04833              0.05013   
4                0.13570            0.06880              0.02564   
..                   ...                ...                  ...   
564              0.41860            0.65990              0.25420   
565              0.21130            0.41070              0.22160   
566              0.19220            0.321

Each row in the table is an observation, and each column is a characteristic. In our example, the columns are characteristics of cell nuclei in breast tumors. The last column represents the target. 'M' means that the observation corresponds to malignant tumor, while 'B' means that the tumor is benign.

In [87]:
breast_cancer.columns

Index(['x.radius_mean', 'x.texture_mean', 'x.perimeter_mean', 'x.area_mean',
       'x.smoothness_mean', 'x.compactness_mean', 'x.concavity_mean',
       'x.concave_pts_mean', 'x.symmetry_mean', 'x.fractal_dim_mean',
       'x.radius_se', 'x.texture_se', 'x.perimeter_se', 'x.area_se',
       'x.smoothness_se', 'x.compactness_se', 'x.concavity_se',
       'x.concave_pts_se', 'x.symmetry_se', 'x.fractal_dim_se',
       'x.radius_worst', 'x.texture_worst', 'x.perimeter_worst',
       'x.area_worst', 'x.smoothness_worst', 'x.compactness_worst',
       'x.concavity_worst', 'x.concave_pts_worst', 'x.symmetry_worst',
       'x.fractal_dim_worst', 'y'],
      dtype='object')

In [88]:
y = breast_cancer.pop('y')
print(y)

0      B
1      B
2      B
3      B
4      B
      ..
564    M
565    M
566    M
567    M
568    M
Name: y, Length: 569, dtype: object


In [ ]:
breast_cancer.columns

In [ ]:
y = y.to_numpy()

In [ ]:
y[y=='B'] = 0
y[y=='M'] = 1
y = y.astype('float32')

TODO: Get X features, normalize/standardize data with mean, std, min, max
Normalize/standardize with sklearn

Data standardization

<h5>Extra exercise</h5>
Build your own standard scaler and normal scaler. 

In [ ]:
from typing import Optional

class StandardScaler:
    def __init__(
        self,
        mean: Optional[float],
        std: Optional[float],
    ) -> None:
        self.mean = mean
        self.std = std

    def fit(self, X, y):
        #write your code here
        pass
    
    def transform(self, X):
        #write your code here
        pass
        
    def fit_transform(self, X, y):
        #write your code here
        pass

In [ ]:
class NormalScaler:
    def __init__(
        self,
        max_value: Optional[float],
        min_value: Optional[float],
    ) -> None:
        self.max_value = max_value
        self.min_value = min_value

    def fit(self, X, y):
        #write your code here
        pass
    
    def transform(self, X):
        #write your code here
        pass
        
    def fit_transform(self, X, y):
        #write your code here
        pass

TODO: add logistic regression exercise with Sklearn with the X and y cancer dataset data
Extra: some statistics (accuracy, recall, F1, confusion matrix)